version: '3'
services:
  mysqldb:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  product-crud:
    container_name: product-crud
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    restart: always
    ports:
      - '$PORT:$PORT'
    env_file:
      - .env
    volumes:
      - /home/ubuntu/file_directory/images:$FILE_STORAGE

volumes: 
  db-config:
  db-data:
